# SSEBop config file
path: 32
row: 34
root: /top/students/GRAD/CE/mrlurtz8/home/ssebop_results
output_root: /top/students/GRAD/CE/mrlurtz8/home/ssebop_results
satellite: LT5
start_date: 19990405
end_date: 19990409
verify_paths: True
agrimet_corrected: False
down_images_only: False
use_existing_images: False
