# SSEBop config file
path: 37
row: 28
root: /home/dgketchum/IrrigationGIS/ssebop_results/
output_root: /home/dgketchum/IrrigationGIS/ssebop_results/
satellite: LC8
start_date: 20130701
end_date: 20130730
verify_paths: True
agrimet_corrected: False
down_images_only: False
use_existing_images: False

