
path: 35
row: 26
root: /data01/images/thermal_analysis
input_root:
output_root:

api_key: 'mapzen-JmKu1BF'
usgs_creds: /data01/images/usgs.txt

satellite: LT5
# Date format; string 'YYYYMMDD'
start_date: 20000401
end_date: 20000930
k_factor: 1.25
verify_paths: True

# Add the path relative to /input_root/
# They will be joined to input_root.
# Parameters mask and polygon are optional
polygons:
mask:
